name: Create ZIP File

on:
  push:
    branches:
      - main  # This will trigger the workflow when you push to the main branch
  workflow_dispatch:  # Allows manual run from GitHub interface

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create a zip of the repository
      run: |
        zip -r project.zip .

    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v2
      with:
        name: project-zip
        path: project.zip